[s, fs, bits] = wavread('E:\绿色软件\Rainmeter_ankty\Rainmeter-1.3-正式版_64位\Skins\Time\简约时间\21.wav');         
s=s-mean(s);                          
s=s/max(abs(s));                      
N=length(s);                           
time=(0:N-1)/fs;                      
clean=s';
ref_noise=.1*randn(1,length(s));
mixed = clean+ref_noise;
mu=0.05;M=2;espon=1e-4;
% [en,wn,yn]=lmsFunc(mu,M,ref_noise,mixed);
% [en,wn,yn]=nlmsFunc(mu,M,ref_noise,mixed,espon);
delta = 1e-7;
lambda = 1;
[en,w]=rls(lambda,M,ref_noise,mixed,delta);
subplot(3,1,1);
plot(clean,'r-');
subplot(3,1,2);
plot(mixed,'r-');
subplot(3,1,3);
plot(en,'r-');
